name: lint
on:
  push:
    branches-ignore:
      - "main"
jobs:
  test_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install and check Lint
        run: |
          cd app
          yarn install
          yarn lint
  test_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Python3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Get Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.4
      - name: Install
        run: poetry install
      - name: Lint with isort
        run: poetry run isort backend
      - name: Lint with black
        run: poetry run black backend
      - name: Lint with flake8
        run: poetry run flake8 backend
      - name: Lint with mypy
        run: poetry run mypy backend
